# SMA Trends
SMA_long = 200
SMA_short = 50

# BULL
BULL_RSI = 15
BULL_RSI_high = 75
BULL_RSI_low = 55

# BEAR
BEAR_RSI = 15
BEAR_RSI_high = 50
BEAR_RSI_low = 20

# ADX
ADX = 3
ADX_high = 50
ADX_low = 20